### ISSUE TITLE
More detailed instructions

### ISSUE THREAD

**Issue by EdanPyx** [GoKillers/libsodium-go#11]
Hello I just thought it might be helpful to include some more detailed instructions like this.

install libsodium here https://download.libsodium.org/doc/installation/index.html
sudo ldconfig
sudo apt-get install pkg-config

go get -d github.com/GoKillers/libsodium-go
cd $GOPATH/src/github.com/GoKillers/libsodium-go
./build.sh

```
package main

import (
        "fmt"
        "github.com/GoKillers/libsodium-go/cryptosign"
)

func main() {

        fmt.Println(cryptosign.CryptoSignBytes())
}

```

**Comment by redragonx** [comment]
This can be a wiki thing too.
