### ISSUE TITLE
Byte mismatch

### ISSUE THREAD

**Issue by KLIM8D** [GoKillers/libsodium-go#15]
Why am I not getting the same bytes in `decPlain` as in the slice `plain`, when decrypting the message?

```go
pk, sk, err := cryptobox.CryptoBoxKeyPair()
if err != 0 {
    panic("error generating keys")
}

fmt.Printf("plain: [% x] \n", plain)
nonce := make([]byte, 24)
binary.BigEndian.PutUint64(nonce, 0)

testMsg, err := cryptobox.CryptoBoxEasy(plain, nonce, pk, sk)
if err != 0 {
    panic("error encrypting")
}
fmt.Printf("testMsg: [% x] \n", testMsg)

decPlain, err := cryptobox.CryptoBoxOpenEasy(testMsg, nonce, pk, sk)
if err != 0 {
    panic("error decrypting")
}
fmt.Printf("decPlain: [% x] \n", decPlain)

```

> plain: [0a 40 0a 15 43 6c 69 65 6e 74 48 65 6c 6c 6f 5f 48 61 6e 64 73 68 61 6b 65 12 20 3b ef 6e e0 ef d4 f2 3e 72 04 bd eb 81 03 06 ed 04 45 ed 4e f3 90 20 37 f5 1f 8f 32 9b 2e fa 17 1a 03 6c 6f 6c 20 2a] 
> 
> testMsg: [c9 aa 34 b9 05 ee 59 b4 e8 8e 91 fa d3 c0 48 dc f8 c2 20 ca b0 6a 85 a4 67 6b 68 78 3b 0f 76 e1 6e d9 ec 1b b1 c6 18 1a e3 45 1f 2f 79 4f b2 13 56 20 b3 f4 44 8a d3 93 80 5f 5f 0f 62 4f 78 d3 7c 30 f3 74 f9 52 a3 80 d0 f8 c0 e0 4f 60 51 6f 52 50]
>  
> decPlain: [4c 90 83 1b 42 91 8d 5e a0 df 41 52 7f 07 75 a6 3b 28 1e 66 f6 e8 b5 75 e1 91 b1 e7 84 a3 51 62 de 7a a2 b5 72 c4 fc d5 e1 3c 57 6c ad 2e 24 1d ec 0b 61 9d f1 f1 20 08 60 1c ad 24 5e ed 84 33 ba 30]

**Comment by redragonx** [comment]
We will look into this.

**Comment by redragonx** [comment]
Can you please provide versions of the Go compiler and native libsodium? @KLIM8D

**Comment by KLIM8D** [comment]
> go version go1.7.1 linux/amd64
> libsodium 1.0.11-1

Below is a full implementation of the code above which reproduces the issue

```go
package main

import (
	"encoding/binary"
	"fmt"
	"github.com/GoKillers/libsodium-go/cryptobox"
)

func main() {
	plain := []byte("42")
	pk, sk, err := cryptobox.CryptoBoxKeyPair()
	if err != 0 {
		panic("error generating keys")
	}

	fmt.Printf("plain: [% x] \n", plain)
	nonce := make([]byte, 24)
	binary.BigEndian.PutUint64(nonce, 0)

	testMsg, err := cryptobox.CryptoBoxEasy(plain, nonce, pk, sk)
	if err != 0 {
		panic("error encrypting")
	}
	fmt.Printf("testMsg: [% x] \n", testMsg)

	decPlain, err := cryptobox.CryptoBoxOpenEasy(testMsg, nonce, pk, sk)
	if err != 0 {
		panic("error decrypting")
	}
	fmt.Printf("decPlain: [% x] \n", decPlain)
}
```

**Comment by redragonx** [comment]
@KLIM8D Does the update work for you?

**Comment by KLIM8D** [comment]
@redragonx Yes this fixed the issue, thanks.
