### ISSUE TITLE
Add support for better detection of libsodium at build time?

### ISSUE THREAD

**Issue by redragonx** [GoKillers/libsodium-go#2]
is this something people would want?

**Comment by jedisct1** [comment]
Yes! It has to at least build on OSX.

Use `pkg-config` to get the correct compilation flags: https://github.com/GoKillers/go-nacl/pull/5

**Comment by redragonx** [comment]
What about Windows? The Go build system is pretty weird to me. I think it can improve with time.

**Comment by redragonx** [comment]
Closing for now.
