### ISSUE TITLE
Hashing an empty slice leads to panic

### ISSUE THREAD

**Issue by theodelrieu** [GoKillers/libsodium-go#28]
Hi, this sample of code causes a crash on commit db67a0d: 

```go
hash, err := generichash.CryptoGenericHash(32, make([]byte, 0), nil)
```

> runtime error: index out of range

I believe this is because of line 56 in crypto_generichash.go:

```go
(*C.uchar)(&in[0]),
```

**Comment by redragonx** [comment]
Will look into this.
